version: '3'

services:
  db:
    image: mariadb
    command : --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: mariaDB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=987654
      - MYSQL_PASSWORD=100298
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    container_name: nextcloud
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=fmanenc
      - NEXTCLOUD_ADMIN_PASSWORD=123456
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.localhost
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=100298
    links:
      - db

  traefik:
    image: traefik:2.4
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

  web:
    build: ./web
    restart: always
    container_name: web_server
    volumes:
      - nextcloud:/var/www/html:ro
      - /data/certs:/etc/nginx/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextapp.rule=Host(`nextcloud.localhost`)"
    links:
      - nextcloud

volumes:
  db:
  nextcloud:
