version: '3'
volumes:
    nextcloud:
    db:
networks:
  next_maria:
  next_web:

services:
    db:
        image: mariadb
        container_name: mariaDB
        command : --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=100298
            - MYSQL_PASSWORD=100298
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        networks:
            - next_maria
            
    nextcloud:
      image: nextcloud:fpm
      container_name: nextcloud_app
      volumes:
          - nextcloud:/var/www/html
      environment:
          - NEXTCLOUD_ADMIN_USER=niferreira
          - NEXTCLOUD_ADMIN_PASSWORD=100298
          - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.36:8090
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
          - MYSQL_PASSWORD=100298
          - MYSQL_HOST=db
      restart: always
      networks:
          - next_maria
          - next_web
    web:
      image: nginx
      container_name: web
      ports:
        - 8090:80
      networks:
        - next_web
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      restart: always
