version: '3.9'
volumes:
    nextcloud:
    db:
networks:
  next_maria:
  next_web:

services:
    db:
        image: mariadb
        container_name: mariaDB
        command : --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=100298
            - MYSQL_PASSWORD=100298
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        networks:
            - next_maria
            
    nextcloud:
      image: nextcloud
      container_name: nextcloud_app
      volumes:
          - nextcloud:/var/www/html
      environment:
          - NEXTCLOUD_ADMIN_USER=fmanenc
          - NEXTCLOUD_ADMIN_PASSWORD=123456
          - NEXTCLOUD_TRUSTED_DOMAINS=localhost
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
          - MYSQL_PASSWORD=100298
          - MYSQL_HOST=db
      restart: always
      labels:
         - "traefik.backend=nextcloud"
         - "traefik.enable=true"
         - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.localhost`)"
         #- "traefik.http.routers.nextcloud.entrypoints=nextcloud"
      depends_on:
          - db
          - traefik
      networks:
          - next_maria
          - next_web

    traefik:
      image: "traefik:v2.4"
      container_name: "traefik"
      command:
          #- "--log.level=DEBUG"
          - "--api.insecure=true"
          #- "--providers.docker=true"
          - "--providers.docker.exposedbydefault=false"
          - "--entrypoints.nextcloud.address=:70"
          - "--entrypoints.web.address=:90"
      labels:
          - "traefik.frontend=nextcloud"
      ports:
          - "8070:70"
          - "80:80"
          - "8080:8080"
          - "90:90"
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
      networks:
          - next_web
      depends_on:
          - db

    whoami:
      image: "traefik/whoami"
      container_name: "whoami"
      labels:
         - "traefik.enable=true"
         - "traefik.http.routers.whoami.rule=Host(`localhost`)"
         - "traefik.http.routers.whoami.entrypoints=web"
         - "traefik.http.routers.whoami.tls=true"
      depends_on:
         - traefik
      networks:
         - next_web
